version: '3.8'

services:
  neo4j-db:
    image: neo4j
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - my-network
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/import
      - neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH=${DB_USERNAME}/${DB_PASSWORD}
    restart: always

  bookapp:
    image: ahmeteminsaglik/ws-neo4j-bookapp:1.3
    container_name: ws-neo4j-bookapp
    ports:
      - "8082:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
    networks:
      - my-network
    depends_on:
      - neo4j-db
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
