name: flutter_book_app
description: Remake Book App Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  logger: ^2.0.2
  shared_preferences: ^2.0.11
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  dio: ^5.3.3
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
  fonts:
    - family: Patrick_Hand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf